swagger: '2.0'
info:
  version: '1.0.0'
  title: 'Better APIs Conference'
  description: 'Example Conference API'
  termsOfService: 'https://betterapis.com/terms'
  contact:
    name: Dave Forgac & Ian Zelikman
    url: https://betterapis.com/info
    email: contact@betterapis.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

schemes:
 - https

consumes:
  - application/json

produces:
  - application/json

paths:
  /talks:
    get:
      summary: Get a list of talks
      description: Retrieve a list of talks
      responses:
        200:
          description: OK

    post:
      summary: Submit a new talk
      description: Results in a new talk submitted
      parameters:
        - name: talk
          in: body
          description: Submit a talk.
          schema:
              type: object
              required: [title, speaker-id, abstract, duration]
              properties:
                id:
                  type: integer
                  description: Unique id for the talk
                title:
                  type: string
                  description: Title for talk
                  minLength: 1
                  maxLength: 144
                speaker-id:
                  type: integer
                  description: Speaker identification in the system
                abstract:
                  type: string
                  minLength: 50
                  maxLength: 500
                  description: The talk abstract
                duration:
                  type: integer
                  default: 60
                  minimum: 45
                  maximum: 90
                  multipleOf: 15
                  description: Requested talk duration
                comments:
                  type: string
                  minLength: 0
                  maxLength: 500
                  description: Additional information added by the speaker
                scheduled-on:
                  type: string
      responses:
        201:
          description: Talk succesfully submitted.
          schema:
            required: [talk-id]
            properties:
              talk-id:
                type: number
                description: Unique Id for the talk in the system
  /speakers:
    get:
      summary: Get a list of speakers
      description: Retrieve a list of speakers
      responses:
        200:
          description: OK
    post:
      summary: Sign up as a speaker
      description: Operation to support speaker registration and submit all details
      parameters:
        - name: speaker
          in: body
          description: New speaker details.
          schema:
            type: object
            required: [first-name, last-name]
            properties:
              id:
                type: integer
                description: Unique id for the speaker
              first-name:
                type: string
                minLength: 1
                maxLength: 25
                description: Speaker first name
              last-name:
                type: string
                minLength: 1
                maxLength: 50
                description: Speaker last name
              comments:
                type: string
                minLength: 50
                maxLength: 200
      responses:
        201:
          description: New speaker registered.
          schema:
            required: [speaker-id]
            properties:
              speaker-id:
                type: number
                description: Unique Id for the talk in the system


